dywee_core_index:
    path:     /
    defaults: { _controller: DyweeCoreBundle:Core:index }

dywee_cron_main:
    path:     /cron-symfony
    defaults: { _controller: DyweeCoreBundle:Cron:main }

dywee_testMail:
    path:     /testMail
    defaults: { _controller: DyweeCoreBundle:Core:testMail }

dywee_robots_txt:
    path:     /robots.txt
    defaults: { _controller: DyweeCoreBundle:Core:robotsTxt }

dywee_update:
    path:     /update
    defaults: { _controller: DyweeCoreBundle:Update:update }

dywee_install:
    path:     /install
    defaults: { _controller: DyweeCoreBundle:Install:install }

dywee_admin_settings:
    path:     /admin6833/settings
    defaults: { _controller: DyweeCoreBundle:Admin:settings }

dywee_admin_homepage:
    path:     /admin
    defaults: { _controller: DyweeCoreBundle:Core:fakeRoute }

admin_dashboard:
    path:     /admin
    defaults: { _controller: DyweeCoreBundle:Core:fakeRoute }