Dywee\CoreBundle\Entity\ParametersManager:
    type: entity
    table: null
    repositoryClass: Dywee\CoreBundle\Entity\ParametersManagerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        value:
            type: string
            length: 255
    lifecycleCallbacks: {  }
